version: "3.8"

services:
  router:
    build: ./router
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
    depends_on:
      - inference
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - geist-network

  inference:
    build: ./inference
    ports:
      - "8080:8080"
    environment:
      - MODEL_PATH=/models/gpt-oss-20b-Q4_K_S.gguf
      - HOST=0.0.0.0
      - PORT=8080
      - CONTEXT_SIZE=4096
      - THREADS=0
      - GPU_LAYERS=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - geist-network

networks:
  geist-network:
    driver: bridge
