"""Add test_run_time to conversation_response

Revision ID: 6e6db6b65802
Revises: 0004
Create Date: 2025-10-27 10:31:49.902161

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6e6db6b65802'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_response', sa.Column('test_run_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_response', 'test_run_time')
    # ### end Alembic commands ###


