name: Build Embedder Service

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment (development, staging, production)"
      version:
        required: true
        type: string
        description: "Version number (semver)"

jobs:
  build_and_push:
    name: Build and Push Embedder Docker Image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/embedder
          tags: |
            type=raw,value=${{ inputs.version }}
            type=raw,value=${{ inputs.environment }}-${{ inputs.version }}
            type=raw,value=${{ inputs.environment }}-latest

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: ./backend/embedder
          file: ./backend/embedder/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.build_and_push.outputs.digest }}

  tagHelm:
    needs: build_and_push
    uses: geistlabs/Geist-Workflows/.github/workflows/tag.yml@master
    with:
      APP: embedder
      VERSION: ${{ inputs.environment }}-${{ inputs.version }}
      ENVIRONMENT: ${{ inputs.environment }}
    secrets:
      PAT: ${{ secrets.PAT }}
